### ISSUE TITLE
Error while running the event handler

### ISSUE THREAD

**Issue by Synthlight** [simwir/Shuttle-Train#30] opened 2016-07-19 02:59 UTC
ShuttleTrain 1.1.2
Error while running the event handler: **ShuttleTrain**/control.lua:52: attempt to index field '?' (a nil value)

All I can tell you is that I was going full-speed in an aircraft laying down landfill over water and this popped up. Not anywhere near a train.
The shuttle train has also been sitting idle (completely safe in the base) & not doing anything for at least 10-15 min; probably more but I lose track of time playing Factorio. :)

So it must have been something that happened to one of the regular trains and the only thing I can think of is this:
Green biters do have a tendency to ball up, stop my trains, and then get angry and either destroy them, or manage to stop them in front of the flame turrets which destroys them.

I loaded the last autosave which was a minute or so beforehand and wasn't able to get the error a second time.

**Comment by simwir** [comment] 2016-07-19 11:56
Hmmm... Well it having something to do with other trains is very possible since the code where the error was thrown is in a event called when any train changes state. The only thing i can think to have caused the error is if the train stopped thereby triggering the event, and then before this mod got to process the event the locomotive was destroyed and therefore a no longer existing entity was accessed.
Do you have a lot of train mods? If so this could mean that more mods are processing the event and thereby increasing the time from when the event was triggered to when I process it.
Anyway let me know if it happens again, but i think it's unlikely

**Comment by Synthlight** [comment] 2016-07-19 12:50
Yea, I agree that's it's very unlikely but I'll keep an eye out anyways.

The only other train mods should be FARL & maybe rail tanker. (Though I don't think rail tanker is enabled since I'm not using it at all right now.) I'll check when I get off work later.

**Comment by simwir** [comment] 2016-07-19 13:53
Unless Rail tanker is completely disabled it still does a little work as seen [here](https://github.com/Choumiko/RailTanker/blob/master/control.lua#L401). But that's probably not worth worrying about.

**Comment by Synthlight** [comment] 2016-07-19 21:23
Other train mods: 

FARL 0.5.35
Honk 2.1.1

Rail tanker isn't enabled and the above two have been with me for most of the long haul. (New save started for 0.13.)

I don't expect anything to happen again but I'll keep a look out.

**Comment by Synthlight** [comment] 2016-07-20 00:43
Reproduced!

Current theory: This crash occurs when a train, without an engine, comes to a stop. This occurs because a middle carriage was destroyed and the rear coasts to a stop.

Steps to reproduce:
1. Make a circle of track.
2. Place engine with 2-3 carriages behind train.
3. Damage second-to-last carriage so it's almost destroyed.
4. Get in train, accelerate, get out, destroy carriage.
5. Once the last carriage coasts to a stop the error occurs.

![reproduced](https://cloud.githubusercontent.com/assets/1075166/16971338/d9f1e8d4-4df0-11e6-8093-aa85c0ac8d12.png)

**Comment by jlaunonen** [comment] 2016-07-28 17:30
Slightly simpler reproduction is to
1. make track long for at least three wagons length,
2. put an engine with one wagon on the track
3. accelerate slightly and disconnect the wagon with 'v'
4. let the wagon stop itself. -> Done.

Happens with trains without engines, and with trains where its only engines are in the middle (between wagons).
The problem in both cases is that front_movers array is empty. In the latter case, back_movers is not empty (as the middle-engine is counted as "back_movers", for a reason or another) so it could be checked for locomotives.

``` lua
local function IsShuttle(movers)
    for _, loco in pairs(movers) do
        if loco.name == "shuttleTrain" then
           return true
        end
    end
    return false
end

-- condition of the on_train_changed_state event then something like:
if event.train.state == defines.train_state.wait_station and
        (IsShuttle(event.train.locomotives["front_movers"]) or
                IsShuttle(event.train.locomotives["back_movers"])) and
        #event.train.schedule.records == 1 then
 ...
```

I admit that is slightly different condition than the original... So depending of the intent of the original condition, the `IsShuttle` could be simplified to only check one-engined trains, and/or simplify the if-clause to not check back_movers at all.

**Comment by simwir** [comment] 2016-08-15 09:46
Fixed in this [commit](https://github.com/simwir/Shuttle-Train/commit/d71f79ebd4c1b20a2b45b097406e3bda1fc306e9)

**Closed as completed by simwir** 2016-08-15 09:46 UTC
Labels: bug
